[package]
name = "dollcode"
version.workspace = true
edition.workspace = true
license-file.workspace = true
authors.workspace = true
repository.workspace = true
description = "Core dollcode encoding and decoding functionality"

[dependencies]
heapless = "0.8.0"
owo-colors = "4.1.0"
